#ifndef UTILS_H
#define UTILS_H

//游戏界面
#define WIDTH (WIDTHNUM * TILESIZE + BTNWIDTH)
#define HEIGHT (TILESIZE * HEIGHTNUM)

//地图
#define TILESIZE 32
#define WIDTHNUM 33
#define HEIGHTNUM 16
#define MAPWIDTH (TILESIZE * WIDTHNUM)
#define MAPHEIGHT (TILESIZE * HEIGHTNUM)

//按钮
#define BTNWIDTH 107
#define BTNHEIGHT 107

//UI
#define INITMONEY 100
#define INITHEALTH 100
#define INITWAVE 10

#define BARWIDTH (5 * TILESIZE + BTNHEIGHT)
#define BARHEIGHT (6 * TILESIZE)
#define DIGIT 5
#define BARNUM 3

#define NUMWIDTH 27
#define NUMHEIGHT 46
#define STATUWIDTH 50
#define STATUHEIGHT 50

#define STATUX 24
#define STATUY 16
#define GAPY 54

#define NUMX 90
#define NUMY 20
#define NUMGAPX 31

//图层
#define MAPZVALUE -10
#define TOWERZVALUE 10
#define MONSTERZVALUE 5
#define BUTTONZVALUE 0
#define PLAYERZVALUE 8

//玩家
#define PLAYERWIDTH TILESIZE
#define PLAYERHEIGHT TILESIZE
#define PLAYERSPEED 150.0

//计时器
#define DELTATIME 16   //单位：ms

#endif // UTILS_H
