#ifndef UTILS_H
#define UTILS_H

//游戏界面
#define WIDTH 1152
#define HEIGHT 648

//地图
#define TILESIZE 32
#define WIDTHNUM 33
#define HEIGHTNUM 16
#define MAPWIDTH 2880
#define MAPHEIGHT 1920

//按钮
#define BTNWIDTH 107
#define BTNHEIGHT 107

//UI
#define INITCAMPHEALTH 10
#define INITPLAYERHEALTH 10
#define INITWAVE 10
#define INITWOOD 0
#define INITSTONE 0
#define INITBRONZE 0
#define INITSILVER 0
#define INITGOLD 0
#define INITRESIN 0

#define UIWIDTH (6 * TILESIZE + BTNHEIGHT)
#define UIHEIGHT (8 * TILESIZE)
#define DIGIT 2
#define BARNUM 8

#define NUMWIDTH 27
#define NUMHEIGHT 46
#define STATUWIDTH 48
#define STATUHEIGHT 48

#define STATUX 24
#define STATUY 16
#define GAPY 54

#define NUMX 90
#define NUMY 20
#define NUMGAPX 31

//图层
#define MAPZVALUE -10
#define TOWERZVALUE 10
#define BULLETZVALUE 10
#define MONSTERZVALUE 5
#define PLAYERZVALUE 5
#define RESOURCEZVALUE -5

//玩家
#define PLAYERWIDTH TILESIZE
#define PLAYERHEIGHT TILESIZE
#define WALKSPEED 150.0
#define ROLLSPEED 500.0

//怪物
#define MONSTER_ATTACK_INTERVAL 2500
//monster1
#define MONSTER1_HEALTH 100.0
#define MONSTER1_SPEED 200.0
#define MONSTER1_GOLD 10
#define MONSTER1_DAMAGE 1
//monster2
#define MONSTER2_HEALTH 200.0
#define MONSTER2_SPEED 40.0
#define MONSTER2_GOLD 20
#define MONSTER2_DAMAGE 2
//monster3
#define MONSTER3_HEALTH 400.0
#define MONSTER3_SPEED 20.0
#define MONSTER3_GOLD 40
#define MONSTER3_DAMAGE 3
//monster4
#define MONSTER4_HEALTH 400.0
#define MONSTER4_SPEED 20.0
#define MONSTER4_GOLD 40
#define MONSTER4_DAMAGE 3

//怪物管理器
#define SPAWNINTERVAL 3.0
#define WAVEINTERVAL 30.0

//tower1
#define TOWER1_MAHEALTH 100
#define TOWER1_BUILCOST 50
#define TOWER1_ATTACKRANGE 150
#define TOWER1_ATTACKINTERVAL 800

//tower2
#define TOWER2_MAHEALTH 100
#define TOWER2_BUILCOST 50
#define TOWER2_ATTACKRANGE 150
#define TOWER2_ATTACKINTERVAL 800

//tower3
#define TOWER3_MAHEALTH 100
#define TOWER3_BUILCOST 50
#define TOWER3_ATTACKRANGE 300
#define TOWER3_ATTACKINTERVAL 800

//资源
#define BIG_STONE_TIME 60
#define TREE_TIME 40

//计时器——玩家
#define POSITION_DELTA 8   //玩家位置更新间隔 单位：ms
#define PICTURE_DELTA 5    //玩家动画更新间隔 单位：ms
#define WALK_FRAME_INTERVAL 80  // 行走80ms 一帧
#define ROLL_FRAME_INTERVAL 50   // 滑行50ms 一帧
#define CUT_FRAME_INTERVAL 100  //砍树100ms 一帧
#define DIG_FRAME_INTERVAL 100  //采石100ms 一帧
#define ROLLTIMES 1.5f  //每次按shift键人物翻滚效果圈数,可以控制滑行时间
#define FIND_TARGET_INTERVAL 100

//计时器——怪物
#define MONSTERDELTA 150
#define MONSTERMOVE 20
#define ATTACKDELAY 1500
#define ATTACKDELTA 100

#endif // UTILS_H
